#!/bin/sh
echo „Creating Symlinks for first usage“
ln -sfn /usr/share/enigma2/Arctic/light/*.* /usr/share/enigma2/Arctic/pic
ln -sfn /usr/share/enigma2/Arctic/light/audioicon /usr/share/enigma2/Arctic/pic
ln -sfn /usr/share/enigma2/Arctic/light/skin_default/*.* /usr/share/enigma2/Arctic/skin_default
rm -f /usr/share/enigma2/Arctic/skin_user_colors.xml
rm /control
rm /postinst
rm /preinst

echo "********************************************************"
echo "*  Arctic installed                               *"
echo "*                                                      *"
echo "*  Restart the Engima2 GUI to activate the plugin      *"
echo "********************************************************"
exit 0
