#!/bin/sh
echo „Installing dependencies“
rm /var/lib/opkg/lock
opkg update
opkg install python-imaging
touch /var/lib/opkg/lock

echo "********************************************************"
echo "*  Dependencies installes                               *"
echo "********************************************************"
exit 0
